// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/tracking.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	repository "github.com/MamangPermen/tracking-service/internal/repository"
	gomock "github.com/golang/mock/gomock"
)

// MockTrackingRepository is a mock of TrackingRepository interface.
type MockTrackingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTrackingRepositoryMockRecorder
}

// MockTrackingRepositoryMockRecorder is the mock recorder for MockTrackingRepository.
type MockTrackingRepositoryMockRecorder struct {
	mock *MockTrackingRepository
}

// NewMockTrackingRepository creates a new mock instance.
func NewMockTrackingRepository(ctrl *gomock.Controller) *MockTrackingRepository {
	mock := &MockTrackingRepository{ctrl: ctrl}
	mock.recorder = &MockTrackingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrackingRepository) EXPECT() *MockTrackingRepositoryMockRecorder {
	return m.recorder
}

// GetResiStatus mocks base method.
func (m *MockTrackingRepository) GetResiStatus(id string) (*repository.Resi, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResiStatus", id)
	ret0, _ := ret[0].(*repository.Resi)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResiStatus indicates an expected call of GetResiStatus.
func (mr *MockTrackingRepositoryMockRecorder) GetResiStatus(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResiStatus", reflect.TypeOf((*MockTrackingRepository)(nil).GetResiStatus), id)
}
